// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Location struct {
	ID         int64     `json:"id"`
	VehicleID  string    `json:"vehicle_id"`
	TripID     string    `json:"trip_id"`
	Latitude   float64   `json:"latitude"`
	Longitude  float64   `json:"longitude"`
	Bearing    float64   `json:"bearing"`
	Speed      float64   `json:"speed"`
	Accuracy   float64   `json:"accuracy"`
	Timestamp  int64     `json:"timestamp"`
	ReceivedAt time.Time `json:"received_at"`
}

type Trip struct {
	ID        string         `json:"id"`
	VehicleID string         `json:"vehicle_id"`
	RouteID   string         `json:"route_id"`
	StartTime string         `json:"start_time"`
	EndTime   sql.NullString `json:"end_time"`
	Status    string         `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
}

type Vehicle struct {
	ID        string    `json:"id"`
	Label     string    `json:"label"`
	AgencyID  string    `json:"agency_id"`
	Active    bool      `json:"active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
