// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const createVehicle = `-- name: CreateVehicle :exec
INSERT INTO vehicles (id, label, agency_id, active)
VALUES (?, ?, ?, ?)
`

type CreateVehicleParams struct {
	ID       string `json:"id"`
	Label    string `json:"label"`
	AgencyID string `json:"agency_id"`
	Active   bool   `json:"active"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) error {
	_, err := q.db.ExecContext(ctx, createVehicle,
		arg.ID,
		arg.Label,
		arg.AgencyID,
		arg.Active,
	)
	return err
}

const getActiveVehicles = `-- name: GetActiveVehicles :many
SELECT v.id, v.label, v.agency_id, v.active, v.created_at, v.updated_at, l.latitude, l.longitude, l.bearing, l.speed, l.timestamp as location_timestamp, l.trip_id
FROM vehicles v
JOIN locations l ON v.id = l.vehicle_id
WHERE v.active = 1
AND l.id = (
    SELECT id FROM locations 
    WHERE vehicle_id = v.id 
    ORDER BY timestamp DESC 
    LIMIT 1
)
`

type GetActiveVehiclesRow struct {
	ID                string    `json:"id"`
	Label             string    `json:"label"`
	AgencyID          string    `json:"agency_id"`
	Active            bool      `json:"active"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	Latitude          float64   `json:"latitude"`
	Longitude         float64   `json:"longitude"`
	Bearing           float64   `json:"bearing"`
	Speed             float64   `json:"speed"`
	LocationTimestamp int64     `json:"location_timestamp"`
	TripID            string    `json:"trip_id"`
}

func (q *Queries) GetActiveVehicles(ctx context.Context) ([]GetActiveVehiclesRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveVehicles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveVehiclesRow
	for rows.Next() {
		var i GetActiveVehiclesRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.AgencyID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Latitude,
			&i.Longitude,
			&i.Bearing,
			&i.Speed,
			&i.LocationTimestamp,
			&i.TripID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestPositionForVehicle = `-- name: GetLatestPositionForVehicle :one
SELECT id, vehicle_id, trip_id, latitude, longitude, bearing, speed, accuracy, timestamp, received_at FROM locations 
WHERE vehicle_id = ? 
ORDER BY timestamp DESC 
LIMIT 1
`

func (q *Queries) GetLatestPositionForVehicle(ctx context.Context, vehicleID string) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLatestPositionForVehicle, vehicleID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.TripID,
		&i.Latitude,
		&i.Longitude,
		&i.Bearing,
		&i.Speed,
		&i.Accuracy,
		&i.Timestamp,
		&i.ReceivedAt,
	)
	return i, err
}

const getVehicle = `-- name: GetVehicle :one
SELECT id, label, agency_id, active, created_at, updated_at FROM vehicles WHERE id = ?
`

func (q *Queries) GetVehicle(ctx context.Context, id string) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, getVehicle, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.AgencyID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLocation = `-- name: InsertLocation :exec
INSERT INTO locations (
    vehicle_id, trip_id, latitude, longitude, bearing, speed, accuracy, timestamp
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertLocationParams struct {
	VehicleID string  `json:"vehicle_id"`
	TripID    string  `json:"trip_id"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	Bearing   float64 `json:"bearing"`
	Speed     float64 `json:"speed"`
	Accuracy  float64 `json:"accuracy"`
	Timestamp int64   `json:"timestamp"`
}

func (q *Queries) InsertLocation(ctx context.Context, arg InsertLocationParams) error {
	_, err := q.db.ExecContext(ctx, insertLocation,
		arg.VehicleID,
		arg.TripID,
		arg.Latitude,
		arg.Longitude,
		arg.Bearing,
		arg.Speed,
		arg.Accuracy,
		arg.Timestamp,
	)
	return err
}
