// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateVehicle(ctx context.Context, arg CreateVehicleParams) error
	GetActiveVehicles(ctx context.Context) ([]GetActiveVehiclesRow, error)
	GetLatestPositionForVehicle(ctx context.Context, vehicleID string) (Location, error)
	GetVehicle(ctx context.Context, id string) (Vehicle, error)
	InsertLocation(ctx context.Context, arg InsertLocationParams) error
}

var _ Querier = (*Queries)(nil)
